var rgb_green, rgb_gray;
draw_set_font(global.fontGUI2)
draw_set_color(c_black)
draw_set_alpha(0.6)
rgb_gray = make_colour_rgb(82, 89, 102)
if (global.curropt == optionid)
    draw_set_color(rgb_gray)
draw_rectangle((x - 2), (y - 1), (x + textoffset - 8), (y + 8), false)
draw_rectangle((x + textoffset - 1), (y - 1), (x + textoffset + w + 1), (y + 8), false)
draw_set_alpha(0.8)
rgb_green = make_colour_rgb(2, 160, 88)
draw_set_color(rgb_green)
draw_rectangle((x + textoffset), y, (x + textoffset + slwidth), (y + 7), false)
draw_set_alpha(1)
draw_set_color(c_black)
draw_text((x + 1), (y - 3), label)
draw_set_color(c_white)
draw_set_alpha(1)
draw_text(x, (y - 4), label)
draw_set_alpha(1)
