if (oControl.mod_fusion == 1)
    pal_swap_set(oControl.TorizoPalette, 1, 0)
if (state == 3)
    draw_sprite(sTorizoIntro, 0, x, y)
if (state == 4)
    draw_sprite(sTorizoIntro, 1, x, y)
if (state == 5)
    draw_sprite(sTorizoIntro, 2, x, y)
if (state == 6)
    draw_sprite(sTorizoIntro, 3, x, y)
draw_sprite(sprite_index, -1, x, y)
shader_reset()
