var omegaSubScr;
draw_set_alpha(1)
if (oControl.mod_fusion == 0)
{
    if (global.currentsuit == 0)
    {
        if (global.hijump == 0)
            draw_sprite_ext(sSubScrPlayer, 0, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        else
            draw_sprite_ext(sSubScrPlayer, 1, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWPI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonWPI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSPI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonPI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonWI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWP, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonWP, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSP, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonP, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSW, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonW, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonS, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannon, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
    }
    if (global.currentsuit == 1)
    {
        if (global.hijump == 0)
            draw_sprite_ext(sSubScrPlayer, 2, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        else
            draw_sprite_ext(sSubScrPlayer, 3, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWPI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonWPI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSPI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonPI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonWI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWP, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonWP, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSP, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonP, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSW, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonW, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonS, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannon, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
    }
    if (global.currentsuit == 2)
    {
        if (global.hijump == 0)
            draw_sprite_ext(sSubScrPlayer, 4, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        else
            draw_sprite_ext(sSubScrPlayer, 5, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWPI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonWPI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSPI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonPI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonWI, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonI, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSWP, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonWP, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sCannonSP, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sCannonP, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonSW, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannonW, 0, (x + 6), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sCannonS, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sCannon, 0, (x + 7), (y + 53), 1, 1, 0, -1, oSubscreenMenu.ealpha)
    }
}
else if (oControl.mod_fusion == 1)
{
    omegaSubScr = 0
    if global.ibeam
    {
        omegaSubScr = 1
        draw_sprite_ext(sSubScrPlayer, 11, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSWPI, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sFCannonWPI, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSPI, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sFCannonPI, 0, (x + 5), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSWI, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sFCannonWI, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSI, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 1 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sFCannonI, 0, (x + 5), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
    }
    if (!omegaSubScr)
    {
        if (global.currentsuit == 0)
            draw_sprite_ext(sSubScrPlayer, 6, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.currentsuit == 1 && oControl.msr_fusionsuit == 0)
            draw_sprite_ext(sSubScrPlayer, 7, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.currentsuit == 2 && oControl.msr_fusionsuit == 0)
            draw_sprite_ext(sSubScrPlayer, 8, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.currentsuit == 1 && oControl.msr_fusionsuit == 1)
            draw_sprite_ext(sSubScrPlayer, 9, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.currentsuit == 2 && oControl.msr_fusionsuit == 1)
            draw_sprite_ext(sSubScrPlayer, 10, x, y, 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSWP, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sFCannonWP, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSP, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 1 && global.sbeam == 0)
            draw_sprite_ext(sFCannonP, 0, (x + 5), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sFCannonSW, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 1 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sFCannonW, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 1)
            draw_sprite_ext(sFCannonS, 0, (x + 4), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
        if (global.ibeam == 0 && global.wbeam == 0 && global.pbeam == 0 && global.sbeam == 0)
            draw_sprite_ext(sFCannon, 0, (x + 5), (y + 56), 1, 1, 0, -1, oSubscreenMenu.ealpha)
    }
}
