list = ds_list_create()
ds_list_read(list, base64_decode(file_text_read_string(argument0)))
i = 0
global.save_room = readline()
global.difficulty = readline()
global.gametime = readline()
global.itemstaken = readline()
global.etanks = readline()
global.mtanks = readline()
global.stanks = readline()
global.ptanks = readline()
global.dnatanks = readline()
global.dnacount = readline()
global.monstersleft = readline()
global.monstersarea = readline()
global.lavastate = readline()
global.mapmarker = readline()
global.mapmarkerx = readline()
global.mapmarkery = readline()
global.seedreceived = readline()
global.floodtraps = readline()
global.tosstraps = readline()
global.shorttraps = readline()
global.emptraps = readline()
global.touhoutraps = readline()
global.ohkotraps = readline()
ds_list_clear(list)
